# Generated by Django 6.0.2 on 2026-02-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
